### ISSUE TITLE
Sieve Driver doesn't working

### ISSUE THREAD

**Issue by mahedicse** [rplessl/roundcube-vacation-plugin#3]
please give details configuration for Sieve driver

**Comment by rplessl** [comment]
never used the siece part

maybe the new version is working now, otherwise patches are welcome.

**Comment by madpsy** [comment]
Do you have details on how to configure it though? I presume you wrote it...

**Comment by crazy4chrissi** [comment]
The "new" version (since 1.0 beta7 released 2009-03-01) of the managesieve plugin includes the functionality to simply define vacation auto-replies.
These are the config options:

```
// Enables separate management interface for vacation responses (out-of-office)
// 0 - no separate section (default),
// 1 - add Vacation section,
// 2 - add Vacation section, but hide Filters section
$config['managesieve_vacation'] = 1;

// Default vacation interval (in days).
// Note: If server supports vacation-seconds extension it is possible
// to define interval in seconds here (as a string), e.g. "3600s".
$config['managesieve_vacation_interval'] = 1;

// Some servers require vacation :addresses to be filled with all
// user addresses (aliases). This option enables automatic filling
// of these on initial vacation form creation.
$config['managesieve_vacation_addresses_init'] = true;

```

So just upgrade the managesieve plugin and drop the vacation plugin. So I guess you guys can also just remove the managesieve driver from your plugin, as it seems to be not working anyway.
